version: '3.1'

services:
  weather-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-analyzer
    restart: on-failure
    depends_on:
      - postgresql
    ports:
      - 8080:8080

  postgresql:
    image: postgres
    container_name: postgresql
    restart: on-failure
    environment:
      POSTGRES_USER: senla
      POSTGRES_PASSWORD: senla
      POSTGRES_DB: weather_analyzer