version: '3.1'

services:
#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring-app
#    restart: unless-stopped
#    depends_on:
#      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    restart: no
    environment:
      POSTGRES_USER: senla
      POSTGRES_PASSWORD: senla
      POSTGRES_DB: weather_analyzer
    ports:
      - 5444:5432